"""Emoji

Available Commands:

.raj"""

from telethon import events

import asyncio





@borg.on(events.NewMessage(pattern=r"\.(.*)", outgoing=True))

async def _(event):

    if event.fwd_from:

        return

    animation_interval = 0.3

    animation_ttl = range(0, 30)

    input_str = event.pattern_match.group(1)

    if input_str == "raj":

        await event.edit(input_str)

        animation_chars = [

            "RAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH",
            
            "◼️RAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH",

            "◼️◼️RAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH",

            "◼️◼️◼️️RAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH",

            "◼️◼️◼️◼️RAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH",

            "‎◼️◼️◼️◼️◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH",

            "◼️◼️◼️◼️◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH",
            
            "◼️◼️◼️◼️◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH",
            
            "◼️◼️◼️◼️◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH",
   
            "◼️◼️◼️◼️◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️",

            "◼️◼️◼️◼️◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️◼️",

            "◼️◼️◼️◼️◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\nRAJDESHMUKHRAJDESHMUKH◼️◼️◼️",

            "◼️◼️◼️◼️◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\nRAJDESHMUKH◼️◼️◼️◼️",

            "◼️◼️◼️◼️◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\n◼️◼️◼️◼️◼️",

            "◼️◼️◼️◼️◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\n◼️RAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\n◼️◼️◼️◼️◼️",

            "◼️◼️◼️◼️◼️\nRAJDESHMUKHRAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\n◼️RAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\n◼️RAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\n◼️◼️◼️◼️◼️",

            "◼️◼️◼️◼️◼️\n◼️RAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\n◼️RAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\n◼️RAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\n◼️◼️◼️◼️◼️",

            "◼️◼️◼️◼️◼️\n◼️◼️RAJDESHMUKHRAJDESHMUKH◼️\n◼️RAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\n◼️RAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\n◼️◼️◼️◼️◼️",

            "◼️◼️◼️◼️◼️\n◼️◼️◼️RAJDESHMUKH◼️\n◼️RAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\n◼️RAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\n◼️◼️◼️◼️◼️",

            "◼️◼️◼️◼️◼️\n◼️◼️◼️◼️◼️\n◼️RAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\n◼️RAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\n◼️◼️◼️◼️◼️",

            "◼️◼️◼️◼️◼️\n◼️◼️◼️◼️◼️\n◼️RAJDESHMUKHRAJDESHMUKH◼️◼️\n◼️RAJDESHMUKHRAJDESHMUKHRAJDESHMUKH◼️\n◼️◼️◼️◼️◼️",

            "◼️◼️◼️◼️◼️\n◼️◼️◼️◼️◼️\n◼️RAJDESHMUKHRAJDESHMUKH◼️◼️\n◼️RAJDESHMUKHRAJDESHMUKH◼️◼️\n◼️◼️◼️◼️◼️",

            "◼️◼️◼️◼️◼️\n◼️◼️◼️◼️◼️\n◼️RAJDESHMUKHRAJDESHMUKH◼️◼️\n◼️RAJDESHMUKH◼️◼️◼️\n◼️◼️◼️◼️◼️",

            "◼️◼️◼️◼️◼️\n◼️◼️◼️◼️◼️\n◼️RAJDESHMUKHRAJDESHMUKH◼️◼️\n◼️◼️◼️◼️◼️\n◼️◼️◼️◼️◼️",

            "◼️◼️◼️◼️◼️\n◼️◼️◼️◼️◼️\n◼️◼️RAJDESHMUKH◼️◼️\n◼️◼️◼️◼️◼️\n◼️◼️◼️◼️◼️",

            "◼️◼️◼️◼️◼️\n◼️◼️◼️◼️◼️\n◼️◼️◼️◼️◼️\n◼️◼️◼️◼️◼️\n◼️◼️◼️◼️◼️",
          
            "◼️◼️◼️◼️\n◼️◼️◼️◼️\n◼️◼️◼️◼️\n◼️◼️◼️◼️",
           
            "◼️◼️◼️\n◼️◼️◼️\n◼️◼️◼️",

            "◼️◼️\n◼️◼️",

            "◼️"
        ]

        for i in animation_ttl:

            await asyncio.sleep(animation_interval)

            await event.edit(animation_chars[i % 30])
